# Azure DevOps Pipeline for Next.js App
trigger:
- main
- develop

pool:
  vmImage: 'ubuntu-latest'

variables:
  nodeVersion: '18.x'
  azureServiceConnection: 'Azure-Service-Connection'
  azureSubscription: 'Your-Azure-Subscription-ID'
  appName: 'afrofeast-heritage-journey'
  resourceGroupName: 'rg-afrofeast-heritage'
  location: 'East US'

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: BuildJob
    displayName: 'Build Next.js App'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: $(nodeVersion)
      displayName: 'Install Node.js'

    - script: |
        npm ci
      displayName: 'Install dependencies'

    - script: |
        npm run build
      displayName: 'Build Next.js app'

    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: '.next'
        artifactName: 'nextjs-build'
      displayName: 'Publish build artifacts'

- stage: Deploy
  displayName: 'Deploy to Azure'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeployJob
    displayName: 'Deploy to Azure App Service'
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            inputs:
              azureSubscription: $(azureSubscription)
              appType: 'webApp'
              appName: $(appName)
              package: '$(Pipeline.Workspace)/nextjs-build'
              deploymentMethod: 'runFromPackage'
